# Generated by Django 5.0.1 on 2024-02-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='session_token',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
